name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: npm install
    - name: Deploy
      env:
        CI: true
      run: npm run deploy --  --cname "aqua.raspberrymonster.top" --email=2194512339@qq.com --branch=gh-pages --gh-username=Raspberry_Monster gh-token=3b6c148e26c3836cd813b1f5040351bfe7e8deb7
